In [58]:
import torch
import numpy as np

In [59]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print(f"Tensor từ list:\n {x_data}\n")

Tensor từ list:
 tensor([[1, 2],
        [3, 4]])



In [60]:
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor:\n {x_ones}\n")

Ones Tensor:
 tensor([[1, 1],
        [1, 1]])



In [61]:
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor:\n {x_rand}\n")

Random Tensor:
 tensor([[0.0829, 0.6393],
        [0.7085, 0.8178]])



In [62]:
print(f"Shape của tensor: {x_rand.shape}")
print(f"Datatype của tensor: {x_rand.dtype}")
print(f"Device lưu trữ tensor: {x_rand.device}")

Shape của tensor: torch.Size([2, 2])
Datatype của tensor: torch.float32
Device lưu trữ tensor: cpu


In [63]:
# 1. Cộng x_data với chính nó
add_result = x_data + x_data
print(f"x_data + x_data: {add_result}")

# 2. Nhân x_data với 5
multiply_result = x_data * 5
print(f"x_data * 5: {multiply_result}")

# 3. Nhân ma trận x_data với x_data.T (ma trận chuyển vị của nó)
transpose_result = x_data @ x_data.T
print(f"x_data @ x_data.T: {transpose_result}")

x_data + x_data: tensor([[2, 4],
        [6, 8]])
x_data * 5: tensor([[ 5, 10],
        [15, 20]])
x_data @ x_data.T: tensor([[ 5, 11],
        [11, 25]])


In [64]:
x = torch.ones(1, requires_grad=True)
print(f"x: {x}")

x: tensor([1.], requires_grad=True)


In [65]:
y = x + 2
print(f"y: {y}")

y: tensor([3.], grad_fn=<AddBackward0>)


In [66]:
z = y * y * 3

In [67]:
z.backward()

In [68]:
linear_layer = torch.nn.Linear(in_features=5, out_features=2)

input_tensor = torch.randn(3, 5) 

output = linear_layer(input_tensor)
print(f"Input shape: {input_tensor.shape}")
print(f"Output shape: {output.shape}")
print(f"Output:\n {output}")

Input shape: torch.Size([3, 5])
Output shape: torch.Size([3, 2])
Output:
 tensor([[ 0.2535,  0.9319],
        [-1.0542, -0.5316],
        [ 0.0926, -0.0765]], grad_fn=<AddmmBackward0>)


In [69]:
embedding_layer = torch.nn.Embedding(num_embeddings=10, embedding_dim=3)

input_indices = torch.LongTensor([1, 5, 0, 8])

embeddings = embedding_layer(input_indices)
print(f"Input shape: {input_indices.shape}")
print(f"Output shape: {embeddings.shape}")
print(f"Embeddings:\n {embeddings}")

Input shape: torch.Size([4])
Output shape: torch.Size([4, 3])
Embeddings:
 tensor([[-1.0969,  0.0732, -1.1025],
        [-1.5452,  0.3246,  0.2523],
        [-0.1380, -0.8979, -1.1999],
        [-0.4756, -0.4578,  0.7528]], grad_fn=<EmbeddingBackward0>)


In [70]:
from torch import nn 

class MyFirstModel(nn.Module): 
    def __init__(self, vocab_size, embedding_dim, hidden_dim, output_dim): 
        super(MyFirstModel, self).__init__()
        self.embedding = nn.Embedding(vocab_size, embedding_dim)
        self.linear = nn.Linear(embedding_dim, hidden_dim)
        self.activation = nn.ReLU()
        self.output_layer = nn.Linear(hidden_dim, output_dim)
    def forward(self, indices):
        embeds = self.embedding(indices)
        hidden = self.activation(self.linear(embeds))
        output = self.output_layer(hidden)
        return output
model = MyFirstModel(vocab_size=100, embedding_dim=16, hidden_dim=8, output_dim=2)
input_data = torch.LongTensor([1, 2, 5, 9])
output_data = model.forward(input_data)
print(f"Output shape: {output_data.shape}")
        

Output shape: torch.Size([4, 2])
